name : hello js 
on : [push]

jobs:
  js-action : 
    runs-on: ubuntu-latest
    steps:
      - name : simple js js-action
        uses : actions/hello-world-javascript-action@v1.1
        with :
          who-to-greet: dev