name : hello js 
on : [push]

jobs:
  js-action : 
    runs-on: ubuntu-latest
    steps:
      - name : simple js js-action
        id : greet
        uses : actions/hello-world-javascript-action@v1.1
        with :
          who-to-greet: dev
      - name : befoure checkout 
        run : ls -a

      - name : checkout
        uses : actions/checkout@v6.0.1
      
      - name : afetr cheakout 
        run : ls -a