name : node
on : [push]
jobs:
  node-version : 
    strategy:
      matrix : 
        node_ver : [4,5,6]
        os : [ubuntu-latest, mac-latest, windowes-latest]
      

    runs-on: ubuntu-latest
    steps:
      - name : actions
        uses: actions/setup-node@v6.2.0
        with:
          node-version: ${{matrix.node_ver}}
      - name : node-version
        run : node -v