name : Shell Commmands

on : [pull_request]

jobs: 
     run-shell-command:
         runs-on : ubuntu-latest
         steps:
             - name : echo a string
               run : echo "I'm groot"
             - name : multine scipt
               run : |
                     node -v
                     npm -v 
     
     prossesor-name : 
       runs-on : ubuntu-latest
       steps:
         - name : prossesor-
           run : |
             import platform
             print(platform.processor())
           shell : python

     not-parrelal : 
       runs-on : windows-latest
       needs : ["run-shell-command","prossesor-name"]
       steps:
         - name : pwd-print
           run : pwd
           shell : bash